version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.9
    steps:
      - checkout
      - run:
          name: Run maven build
          command: mvn clean install
      - run: find .
      - store_artifacts:
          path: ./client/target/*.jar
      - store_artifacts:
          path: ./server/target/*.jar
