version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.9
    steps:
      - checkout
      - run:
          name: Get commit hash
          command: echo "${CIRCLE_SHA1:0:7}"
      - run:
          name: Run maven build
          command: mvn clean install -Dcommit.hash="${CIRCLE_SHA1:0:7}"
      - run:
          name: Copy artifacts
          command: mkdir artifacts && cp */target/*shaded*.jar artifacts
      - store_artifacts:
          path: artifacts
